export const hotelTags = [
    { label: 'Boutique', value: 'Boutique' },
    { label: 'Resort', value: 'Resort' },
    { label: 'Budget', value: 'Budget' },
    { label: 'Luxury', value: 'Luxury' },
    { label: 'Family-friendly', value: 'Family-friendly' },
    { label: 'Romantic', value: 'Romantic' },
    { label: 'Pet-friendly', value: 'Pet-friendly' },
    { label: 'Business', value: 'Business' },
    { label: 'Beach', value: 'Beach' },
    { label: 'Mountain lodge', value: 'Mountain lodge' },
    { label: 'City center', value: 'City center' },
    { label: 'Bed and breakfast', value: 'Bed and breakfast' },
    { label: 'Historic', value: 'Historic' },
    { label: 'Ski resort', value: 'Ski resort' },
    { label: 'Spa', value: 'Spa' },
    { label: 'Airport', value: 'Airport' },
    { label: 'Waterfront', value: 'Waterfront' },
    { label: 'Golf resort', value: 'Golf resort' },
    { label: 'Casino hotel', value: 'Casino hotel' },
    { label: 'Hostel', value: 'Hostel' },
];

export const breakfastRestaurantTags = [
    { label: 'Cafe', value: 'Cafe' },
    { label: 'Bakery', value: 'Bakery' },
    { label: 'Brunch', value: 'Brunch' },
    { label: 'Coffee', value: 'Coffee' },
    { label: 'Healthy', value: 'Healthy' },
    { label: 'Quick', value: 'Quick' },
    { label: 'Buffet', value: 'Buffet' },
    { label: 'Outdoor seating', value: 'Outdoor seating' },
    { label: 'Vegetarian', value: 'Vegetarian' },
    { label: 'Vegan', value: 'Vegan' },
    { label: 'Breakfast burrito', value: 'Breakfast burrito' },
    { label: 'Breakfast sandwich', value: 'Breakfast sandwich' },
    { label: 'Smoothie and juice', value: 'Smoothie and juice' },
    { label: 'Waffle', value: 'Waffle' },
    { label: 'French pastry', value: 'French pastry' },
    { label: 'Traditional breakfast', value: 'Traditional breakfast' },
    { label: 'Hotel breakfast buffet', value: 'Hotel breakfast buffet' },
    { label: 'Upscale brunch', value: 'Upscale brunch' },
    { label: 'Country-style diner', value: 'Country-style diner' }
];

export const lunchRestaurantTags = [
    { label: 'Fast food', value: 'Fast food' },
    { label: 'Casual', value: 'Casual' },
    { label: 'Fine dining', value: 'Fine dining' },
    { label: 'Ethnic', value: 'Ethnic' },
    { label: 'Sandwiches', value: 'Sandwiches' },
    { label: 'Vegetarian', value: 'Vegetarian' },
    { label: 'Seafood', value: 'Seafood' },
    { label: 'Outdoor seating', value: 'Outdoor seating' }
];

export const dinnerRestaurantTags = [
    { label: 'Fine dining', value: 'Fine dining' },
    { label: 'Steakhouses', value: 'Steakhouses' },
    { label: 'Seafood restaurants', value: 'Seafood restaurants' },
    { label: 'Italian restaurants', value: 'Italian restaurants' },
    { label: 'Mexican restaurants', value: 'Mexican restaurants' },
    { label: 'Chinese restaurants', value: 'Chinese restaurants' },
    { label: 'Japanese restaurants', value: 'Japanese restaurants' },
    { label: 'Thai restaurants', value: 'Thai restaurants' },
    { label: 'Indian restaurants', value: 'Indian restaurants' },
    { label: 'Greek restaurants', value: 'Greek restaurants' },
    { label: 'French restaurants', value: 'French restaurants' },
    { label: 'Vietnamese restaurants', value: 'Vietnamese restaurants' },
    { label: 'Korean restaurants', value: 'Korean restaurants' },
    { label: 'Brazilian steakhouses', value: 'Brazilian steakhouses' },
    { label: 'Middle Eastern restaurants', value: 'Middle Eastern restaurants' },
    { label: 'Fusion restaurants', value: 'Fusion restaurants' },
    { label: 'Gastropubs', value: 'Gastropubs' },
    { label: 'Wine bars', value: 'Wine bars' },
    { label: 'Rooftop restaurants', value: 'Rooftop restaurants' },
    { label: 'Farm-to-table restaurants', value: 'Farm-to-table restaurants' }, 
    { label: 'Fine dining', value: 'Fine dining' },
    { label: 'Steakhouse', value: 'Steakhouse' },
    { label: 'Italian', value: 'Italian' },
    { label: 'Chinese', value: 'Chinese' },
    { label: 'Mexican', value: 'Mexican' },
    { label: 'Sushi', value: 'Sushi' },
    { label: 'Seafood', value: 'Seafood' },
    { label: 'Outdoor seating', value: 'Outdoor seating' },
  ];
  
  export const activityTags = [
    { label: 'Museums', value: 'Museums' },
    { label: 'Art galleries', value: 'Art galleries' },
    { label: 'Zoos', value: 'Zoos' },
    { label: 'Aquariums', value: 'Aquariums' },
    { label: 'Botanical gardens', value: 'Botanical gardens' },
    { label: 'National parks', value: 'National parks' },
    { label: 'Historic sites', value: 'Historic sites' },
    { label: 'Sporting events', value: 'Sporting events' },
    { label: 'Concerts', value: 'Concerts' },
    { label: 'Theaters', value: 'Theaters' },
    { label: 'Theme parks', value: 'Theme parks' },
    { label: 'Water parks', value: 'Water parks' },
    { label: 'Amusement parks', value: 'Amusement parks' },
    { label: 'Escape rooms', value: 'Escape rooms' },
    { label: 'Go-kart racing', value: 'Go-kart racing' },
    { label: 'Mini-golf courses', value: 'Mini-golf courses' },
    { label: 'Laser tag facilities', value: 'Laser tag facilities' },
    { label: 'Movie theaters', value: 'Movie theaters' },
    { label: 'Virtual reality experiences', value: 'Virtual reality experiences' },
    { label: 'Outdoor adventures', value: 'Outdoor adventures' }, 
    { label: 'Museum', value: 'Museum' },
    { label: 'Art', value: 'Art' },
    { label: 'Nature', value: 'Nature' },
    { label: 'Sports', value: 'Sports' },
    { label: 'Entertainment', value: 'Entertainment' },
    { label: 'Landmarks', value: 'Landmarks' },
    { label: 'Tours', value: 'Tours' },
    { label: 'Classes', value: 'Classes' },
  ];
  
  
const tagOptions = {
    'Hotel': hotelTags,
    'Breakfast Restaurant': breakfastRestaurantTags,
    'Lunch Restaurant': lunchRestaurantTags,
    'Activity': activityTags,
    'Dinner Restaurant': dinnerRestaurantTags,
};